'use client';
import { useEffect, useState } from 'react';
import { api, ApiError } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Toast } from '@/components/ui/toast';

const parseBrlInput = (value: string) => {
  const digits = value.replace(/\D/g, '');
  return digits ? Number(digits) / 100 : 0;
};

const formatBRL = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number.isFinite(value) ? value : 0);

export default function CampaignsPage(){
const [items,setItems]=useState<any[]>([]); const [toast,setToast]=useState(''); const [toastType,setToastType]=useState<'success'|'error'>('success'); const [editingId,setEditingId]=useState<string|null>(null); const [loadingSubmit,setLoadingSubmit]=useState(false); const [form,setForm]=useState({title:'',description:'',startDate:'',endDate:'',minimumValuePerCoupon:0});
const load=()=>api('/campaigns').then(setItems); useEffect(()=>{void load();},[]);
const valid=()=>{const now=new Date();const s=new Date(form.startDate);const e=new Date(form.endDate); if(e<s){setToastType('error');setToast('Data final não pode ser menor que data inicial.');return false;} if(e<now){setToastType('error');setToast('Data final não pode ser menor que data atual.');return false;} if(form.minimumValuePerCoupon<=0){setToastType('error');setToast('Valor mínimo por cupom deve ser maior que zero.');return false;} return true;};
return <div className='space-y-4'><Toast message={toast} type={toastType} onClose={()=>setToast('')}/><h1 className='text-2xl font-bold'>Campanhas</h1><div className='ui-card grid gap-3 md:grid-cols-2'>
{['title','description','startDate','endDate'].map((k)=><label key={k} className='space-y-1'><span className='ui-label'>{k==='title'?'Nome':k==='description'?'Descrição':k==='startDate'?'Data início':'Data final'}</span><input type={k.includes('Date')?'datetime-local':'text'} className='ui-input' value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
<label className='space-y-1 md:col-span-2'><span className='ui-label'>Valor mínimo por cupom</span><input inputMode='numeric' className='ui-input' value={form.minimumValuePerCoupon?formatBRL(form.minimumValuePerCoupon):''} onChange={e=>setForm({...form,minimumValuePerCoupon:parseBrlInput(e.target.value)})} placeholder='R$ 0,00'/></label>
<Button disabled={loadingSubmit} className='w-full sm:w-fit' onClick={async()=>{if(!valid())return; setLoadingSubmit(true); try { if(editingId){await api(`/campaigns/${editingId}`,{method:'PUT',body:JSON.stringify(form)});setToastType('success');setToast('Campanha alterada com sucesso.');} else {await api('/campaigns',{method:'POST',body:JSON.stringify(form)});setToastType('success');setToast('Campanha criada com sucesso.');} setEditingId(null); setForm({title:'',description:'',startDate:'',endDate:'',minimumValuePerCoupon:0}); void load(); } catch(e){setToastType('error');setToast(e instanceof ApiError ? e.message : 'Erro ao salvar campanha.');} finally {setLoadingSubmit(false);} }}>{loadingSubmit?'Salvando...':editingId?'Salvar alterações':'Criar'}</Button></div>
<div className='ui-table-wrap max-h-[55vh]'><table className='ui-table'><thead><tr><th className='ui-th'>Campanha</th><th className='ui-th'>Status</th><th className='ui-th'>Ações</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td className='ui-td'>{i.title}</td><td className='ui-td'>{i.active?'Ativa':'Pausada/Finalizada'}</td><td className='ui-td'><div className='flex min-w-[520px] flex-wrap gap-2'><Button variant='secondary' onClick={()=>{setEditingId(i.id);setForm({...i,startDate:i.startDate.slice(0,16),endDate:i.endDate.slice(0,16),minimumValuePerCoupon:Number(i.minimumValuePerCoupon)});}}>Editar</Button><Button onClick={async()=>{try{await api(`/campaigns/${i.id}/activate`,{method:'PATCH'});setToastType('success');setToast('Campanha ativada com sucesso.');void load();}catch(e){setToastType('error');setToast('Erro ao ativar campanha.');}}}>Ativar</Button><Button onClick={async()=>{try{await api(`/campaigns/${i.id}/pause`,{method:'PATCH'});setToastType('success');setToast('Campanha pausada com sucesso.');void load();}catch(e){setToastType('error');setToast('Erro ao pausar campanha.');}}}>Pausar</Button><Button onClick={async()=>{if(!confirm('Deseja finalizar campanha e executar o sorteio automático?'))return;try{await api(`/campaigns/${i.id}/finalize`,{method:'PATCH'});setToastType('success');setToast('Campanha finalizada e sorteio realizado.');void load();}catch(e){setToastType('error');setToast(e instanceof ApiError?e.message:'Erro ao finalizar campanha.');}}}>Finalizar</Button><Button variant='danger' onClick={async()=>{try{await api(`/campaigns/${i.id}`,{method:'DELETE'});setToastType('success');setToast('Campanha excluída com sucesso.');void load();}catch(e){setToastType('error');setToast('Esta campanha não pode ser excluída porque já possui compras ou cupons vinculados.');}}}>Excluir</Button></div></td></tr>)}</tbody></table></div></div>
}
