'use client';
import { useEffect, useState } from 'react';
import { api, ApiError } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Toast } from '@/components/ui/toast';

export default function CampaignsPage(){
const [items,setItems]=useState<any[]>([]); const [toast,setToast]=useState(''); const [editingId,setEditingId]=useState<string|null>(null); const [form,setForm]=useState({title:'',description:'',startDate:'',endDate:'',minimumValuePerCoupon:0});
const load=()=>api('/campaigns').then(setItems); useEffect(()=>{void load();},[]);
const valid=()=>{const now=new Date();const s=new Date(form.startDate);const e=new Date(form.endDate); if(e<s){setToast('Data final não pode ser menor que data inicial.');return false;} if(e<now){setToast('Data final não pode ser menor que data atual.');return false;} if(form.minimumValuePerCoupon<=0){setToast('Valor mínimo por cupom deve ser maior que zero.');return false;} return true;};
return <div className='space-y-4'><Toast message={toast}/><h1 className='text-2xl font-bold'>Campanhas</h1><div className='ui-card grid gap-3 md:grid-cols-2'>
{['title','description','startDate','endDate'].map((k)=><label key={k} className='space-y-1'><span className='ui-label'>{k==='title'?'Nome':k==='description'?'Descrição':k==='startDate'?'Data início':'Data final'}</span><input type={k.includes('Date')?'datetime-local':'text'} className='ui-input' value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
<label className='space-y-1 md:col-span-2'><span className='ui-label'>Valor mínimo por cupom</span><input type='number' min='0.01' step='0.01' className='ui-input' value={form.minimumValuePerCoupon||''} onChange={e=>setForm({...form,minimumValuePerCoupon:Number(e.target.value)})}/></label>
<Button className='w-fit' onClick={async()=>{if(!valid())return; if(editingId){await api(`/campaigns/${editingId}`,{method:'PUT',body:JSON.stringify(form)});setToast('Campanha alterada com sucesso.');} else {await api('/campaigns',{method:'POST',body:JSON.stringify(form)});setToast('Campanha criada com sucesso.');} setEditingId(null); setForm({title:'',description:'',startDate:'',endDate:'',minimumValuePerCoupon:0}); void load();}}>{editingId?'Salvar alterações':'Criar'}</Button></div>
<div className='ui-table-wrap max-h-[55vh]'><table className='ui-table'><thead><tr><th className='ui-th'>Campanha</th><th className='ui-th'>Ações</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td className='ui-td'>{i.title}</td><td className='ui-td flex gap-2'><Button variant='secondary' onClick={()=>{setEditingId(i.id);setForm({...i,startDate:i.startDate.slice(0,16),endDate:i.endDate.slice(0,16),minimumValuePerCoupon:Number(i.minimumValuePerCoupon)});}}>Editar</Button><Button onClick={async()=>{await api(`/campaigns/${i.id}/toggle-active`,{method:'PATCH'});void load();}}>Alterar status</Button><Button variant='danger' onClick={async()=>{try{await api(`/campaigns/${i.id}`,{method:'DELETE'});setToast('Campanha excluída com sucesso.');void load();}catch(e){if(e instanceof ApiError){setToast('Esta campanha não pode ser excluída porque já possui compras ou cupons vinculados.');}}}}>Excluir</Button></td></tr>)}</tbody></table></div></div>
}
